{
 "title": "SQLServer:Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Server", "query": "mssql" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT dbo.udf_get_sql_server_version(sqlserver_product_version) AS Version\r\nFROM dbo.mssql247_sql_instance"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT sqlserver_edition AS Edition\r\nFROM dbo.mssql247_sql_instance"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT sql_cpu + (100 - (idle_cpu + sql_cpu)) AS CPU , collection_datetime_utc\r\nFROM (SELECT record.value('(./Record/SchedulerMonitorEvent/SystemHealth/ProcessUtilization)[1]', 'int') sql_cpu ,\r\n      record.value('(./Record/SchedulerMonitorEvent/SystemHealth/SystemIdle)[1]', 'int') idle_cpu, collection_datetime_utc\r\nFROM (SELECT ring_buffer_address, ring_buffer_type, collection_datetime_utc, CAST(record AS XML) record \r\n    FROM dbo.mssql247_os_ring_buffers\r\n    WHERE ring_buffer_type IN ('RING_BUFFFER_RESOUCE_MONITOR', 'RING_BUFFER_SCHEDULER_MONITOR')) AS ss ) ss\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nORDER BY collection_datetime_utc"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT ((total_physical_memory_kb * 1. - available_physical_memory_kb * 1.) / total_physical_memory_kb) * 100. AS Memory\r\nFROM dbo.mssql247_os_sys_memory\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nORDER BY collection_datetime_utc"
    }
   ]
  },
  {
   "title": "Total Server Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT total_physical_memory_kb AS [Total Server Memory]\r\nFROM dbo.mssql247_os_sys_memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT physical_memory_in_use_kb AS [SQL Server Memory (in use)]\r\nFROM dbo.mssql247_os_process_memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT cpu_count AS [CPU Count]\r\nFROM dbo.mssql247_os_sys_info"
    }
   ]
  },
  {
   "title": "Restoring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(*) AS [RESTORING]\r\nFROM dbo.mssql247_databases\r\nWHERE state = 'RESTORING'\r\nAND collection_datetime_utc = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_databases)"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DBA",
     "rawSql": "SELECT REPLACE(volume_name, '(C:)', '') + ' (' + volume_mount_point + ')' volume_mount_point, ((total_size_kb - size_remaining_kb) / (total_size_kb * 1.) * 100.) FROM dbo.mssql247_os_volumes\r\nWHERE collection_datetime_utc = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_os_volumes)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT cntr_value AS [Active Temp Tables] FROM dbo.mssql247_performance_counters\r\nWHERE (counter_name =  'Active Temp Tables')\r\nAND $__timeFilter(collection_datetime_utc)\r\nORDER BY collection_datetime_utc"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "DECLARE @LastSnapshotTStamp DATETIME \r\nSET @LastSnapshotTStamp = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_performance_counters p)\r\nDECLARE @SecondToTheLastSnapshotTStamp DATETIME \r\nSET @SecondToTheLastSnapshotTStamp = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_performance_counters p\r\n                                        WHERE collection_datetime_utc <> @LastSnapshotTStamp)\r\nDECLARE @SnapshotDateDiff INT = DATEDIFF(SECOND, @SecondToTheLastSnapshotTStamp, @LastSnapshotTStamp)\r\n;WITH cteBatchRequestsCapturedLast (value)\r\nAS (SELECT TOP 1 cntr_value AS 'Batch Requests/sec'\r\n    FROM dbo.mssql247_performance_counters p\r\n    WHERE object_name = 'SQLServer:SQL Statistics'\r\n    AND counter_name = 'Batch Requests/sec'\r\n    AND collection_datetime_utc = @LastSnapshotTStamp),\r\ncteBatchRequestsCapturedSecondToTheLast (value)\r\nAS (SELECT TOP 1 cntr_value AS 'Batch Requests/sec'\r\n    FROM dbo.mssql247_performance_counters p\r\n    WHERE object_name = 'SQLServer:SQL Statistics'\r\n    AND counter_name = 'Batch Requests/sec'\r\n    AND collection_datetime_utc = @SecondToTheLastSnapshotTStamp)\r\nSELECT CASE WHEN @SnapshotDateDiff = 0 THEN ((SELECT value FROM cteBatchRequestsCapturedLast) - \r\n            (SELECT value FROM cteBatchRequestsCapturedSecondToTheLast)) ELSE ((SELECT value FROM cteBatchRequestsCapturedLast) - \r\n            (SELECT value FROM cteBatchRequestsCapturedSecondToTheLast)) / @SnapshotDateDiff END AS 'Batch Requests/sec'"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(*) AS [Blocked]\r\nFROM dbo.mssql247_blocked_query_stats\r\nWHERE blocked_query_status = 1"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(DISTINCT name) AS [Databases]\r\nFROM dbo.mssql247_databases\r\nWHERE collection_datetime_utc = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_databases)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT SUM(size * 8) AS [Total Data File Size]\r\nFROM dbo.mssql247_master_files\r\nWHERE collection_datetime_utc = (SELECT MAX(collection_datetime_utc)\r\n                                  FROM dbo.mssql247_master_files)\r\nAND type = 0"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT SUM(size * 8) AS [Total Log File Size]\r\nFROM dbo.mssql247_master_files\r\nWHERE collection_datetime_utc = (SELECT MAX(collection_datetime_utc)\r\n                                  FROM dbo.mssql247_master_files)\r\nAND type = 1"
    }
   ]
  },
  {
   "title": "Suspect",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(*) AS [SUSPECT]\r\nFROM dbo.mssql247_databases\r\nWHERE state = 'SUSPECT'\r\nAND collection_datetime_utc = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_databases)"
    }
   ]
  },
  {
   "title": "Emergency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(*) AS [EMERGENCY]\r\nFROM dbo.mssql247_databases\r\nWHERE state = 'EMERGENCY'\r\nAND collection_datetime_utc = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_databases)"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(*) AS [OFFLINE]\r\nFROM dbo.mssql247_databases\r\nWHERE state = 'OFFLINE'\r\nAND collection_datetime_utc = (SELECT MAX(collection_datetime_utc) FROM dbo.mssql247_databases)"
    }
   ]
  },
  { "title": "Resource Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT sql_cpu, idle_cpu, (100 - (sql_cpu+idle_cpu)) other, collection_datetime_utc\r\nFROM (SELECT record.value('(./Record/SchedulerMonitorEvent/SystemHealth/ProcessUtilization)[1]', 'int') sql_cpu ,\r\n      record.value('(./Record/SchedulerMonitorEvent/SystemHealth/SystemIdle)[1]', 'int') idle_cpu, collection_datetime_utc\r\nFROM (SELECT ring_buffer_address, ring_buffer_type, collection_datetime_utc, CAST(record AS XML) record \r\n    FROM dbo.mssql247_os_ring_buffers\r\n    WHERE ring_buffer_type IN ('RING_BUFFFER_RESOUCE_MONITOR', 'RING_BUFFER_SCHEDULER_MONITOR')) AS ss ) ss\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nORDER BY collection_datetime_utc"
    }
   ]
  },
  {
   "title": "Disk Activity:Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT SUM((io_stall_read_ms)/num_of_reads) avg_read_stall_ms,\r\n  SUM((io_stall_write_ms)/(num_of_writes+1)) avg_write_stall_ms,\r\n  collection_datetime_utc\r\nFROM dbo.mssql247_file_io_stats\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nGROUP BY collection_datetime_utc\r\nORDER BY collection_datetime_utc ASC"
    }
   ]
  },
  { "title": "Disk Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Disk Activity:Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT SUM((io_stall_read_ms)/num_of_reads) avg_read_stall_ms,\r\n  SUM((io_stall_write_ms)/(num_of_writes+1)) avg_write_stall_ms,\r\n  collection_datetime_utc\r\nFROM dbo.mssql247_file_io_stats\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nGROUP BY collection_datetime_utc\r\nORDER BY collection_datetime_utc ASC"
    }
   ]
  },
  {
   "title": "Disk Activity:Read & Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT SUM((num_of_bytes_read)/(num_of_reads + 1)) AS avg_reads_kb,\r\n  SUM((num_of_bytes_written)/(num_of_writes + 1)) AS avg_writes_kb,\r\n  collection_datetime_utc\r\nFROM dbo.mssql247_file_io_stats\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nGROUP BY collection_datetime_utc\r\nORDER BY collection_datetime_utc"
    }
   ]
  },
  { "title": "Buffer Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Buffer Pool:Manager",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT committed_memory_kb AS bpool_committed_kb, \r\n  committed_target_kb AS bpool_target_kb,\r\n  collection_datetime_utc\r\nFROM dbo.mssql247_os_sys_info\r\nWHERE $__timeFilter(collection_datetime_utc)\r\nORDER BY collection_datetime_utc"
    }
   ]
  },
  { "title": "Blocking Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Blocking Activity:Trend",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT COUNT(*) blocked_sessions, DATEADD(HOUR, -8, start_time)\r\nFROM dbo.mssql247_blocked_query_stats\r\nGROUP BY start_time\r\nORDER BY start_time"
    }
   ]
  },
  {
   "title": "Blocking Activity:Blocked Sessions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": "SELECT session_id, start_time, sql_text, blocking_session_id, wait_type, wait_time, host_name, login_name, program_name, client_net_address, open_transaction_count, transaction_id\r\nFROM dbo.mssql247_blocked_query_stats\r\nWHERE blocked_query_status <> 0"
    }
   ]
  },
  {
   "title": "Blocking Activity:Tree View",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "dataset": "AdventureWorks",
     "rawSql": ";WITH cteHeadBlocker (blocking_tree_group, session_id, blocking_spid, blocking_level)\r\nAS (SELECT spid, spid, blocked, 1 FROM sys.sysprocesses s \r\n    WHERE blocked = 0\r\n    AND EXISTS (SELECT blocking_session_id FROM sys.dm_exec_requests    \r\n                    WHERE blocking_session_id <> 0\r\n                    AND blocking_session_id = s.spid)\r\n    UNION ALL\r\n    SELECT blocking_tree_group, r.session_id, r.blocking_session_id, blocking_level + 1 FROM sys.dm_exec_requests r\r\n    INNER JOIN cteHeadBlocker blocker \r\n    ON r.blocking_session_id = blocker.session_id\r\n    AND r.blocking_session_id <> 0)\r\nSELECT cteHeadBLocker.session_id, CASE WHEN cteHeadBlocker.blocking_spid = 0 THEN 'HEAD BLOCKER' ELSE 'BLOCKED' END, t.text, cteHeadBlocker.blocking_spid, cteHeadBlocker.blocking_level, s.spid FROM cteHeadBLocker\r\nINNER JOIN sys.sysprocesses s ON cteHeadBlocker.session_id = s.spid\r\nINNER JOIN sys.dm_exec_connections c ON c.session_id = s.spid\r\nCROSS APPLY sys.dm_exec_sql_text(c.most_recent_sql_handle) t\r\nORDER BY cteHeadBlocker.blocking_tree_group ASC, cteHeadBlocker.blocking_level ASC"
    }
   ]
  }
 ]
}